#!/bin/bash

# Fail if systemd D-Bus is not listening
/usr/bin/ss -xl | /usr/bin/grep -q '/run/systemd/private' || exit 1
# Also ensure systemctl can talk
/usr/bin/systemctl show -p Version >/dev/null 2>&1 || exit 1
exit 0
